config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  resources :reports do
    resources :comments, only: :create
    collection do
      get "search"
    end
  end
  resources :boards, only: [:index, :new, :create, :destroy] do
    resources :checks, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :checks
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :user
  belongs_to :board
  validates :user_id, presence: true, uniqueness: {scope: :board_id}
  validates :board_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :report
  belongs_to :user
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  has_many :comments

  def self.search(search)
    if search != ""
      Report.where('note LIKE(?)', "%#{search}%")
    else
      Report.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reports
  has_many :comments
  has_many :checks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resourse)
    reports_path
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :move_to_top

  def index
    @boards = Board.includes(:user).order("created_at DESC")
  end

  def new
    @board = Board.new
  end

  def create
    Board.create(board_params)
    redirect_to boards_path
  end
  
  def destroy
    board = Board.find(params[:id])
    if board.user_id == current_user.id
      board.destroy
      redirect_to boards_path
    end
  end

  private
  def board_params
    params.permit(:content).merge(user_id: current_user.id)
  end

  def move_to_top
    unless user_signed_in?
      redirect_to root_path
    end
  end

end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController

  def create
    @check = Check.new(user_id: current_user.id, board_id: params[:board_id])
    @check.save
    redirect_to boards_path
  end

  def destroy
    @check = Check.find_by(user_id: current_user.id, board_id: params[:board_id])
    @check.destroy
    redirect_to boards_path
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/reports/#{comment.report.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, report_id: params[:report_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :move_to_top

  def index
    @reports = Report.includes(:user).order("created_at DESC")
  end

  def new
    @report = Report.new
  end

  def create
    Report.create(report_params)
    redirect_to reports_path
  end
  
  def show
    @report = Report.find(params[:id])
    @comment = Comment.new
    @comments = @report.comments.includes(:user)
  end

  def edit
    @report = Report.find(params[:id])
    if @report.user_id != current_user.id
      redirect_to reports_path
    end
  end

  def update
    report = Report.find(params[:id])
    report.update(report_params)
    redirect_to reports_path
  end

  def destroy
    report = Report.find(params[:id])
    if report.user_id == current_user.id
      report.destroy
      redirect_to reports_path
    end
  end

  def search
    @reports = Report.search(params[:keyword])
  end

  private
  def report_params
    params.require(:report).permit(:client, :client_person, :business, :result, :note).merge(user_id: current_user.id)
  end

  def move_to_top
    unless user_signed_in?
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/boards/index.html.erb
<div class="boards-contents">
  <div class="boards-form">
    <%= form_with(model: @board, local: true) do |f| %>
      <%= f.text_area :content, placeholder: "連絡事項を入力", class:"form-text"%><br>
      <%= f.submit '投稿', class:"send" %>
    <% end %>
  </div>

  <% @boards.each do |board| %>
    <div class="boards-contents-article">
      <h4 class="writer">投稿者：<%= board.user.name %><span><h4>
      <p class="message"><%= board.content %></p>
      <% if Check.find_by(user_id: current_user.id, board_id: board.id)  %>
        <%= link_to board_check_path(board.id, current_user.id), method: :delete do %>
          <i class="fa fa-check on" aria-hidden="true"></i><a class="count"><%= board.checks.count %></a>
        <% end %>
      <% else %>
        <%= link_to board_checks_path(board.id), method: :post do %>
          <i class="fa fa-check off" aria-hidden="true"></i><a class="count"><%= board.checks.count %></a>
        <% end %>
      <% end %>
      <% if current_user.id == board.user_id %>
        <%= link_to board_path(board.id), method: :delete do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      <% end %>
      <br><p class="date"><%= board.created_at.strftime("%Y-%m-%d %H:%M") %></p>
    </div>
  <% end %>
</div>

app/views/home/top.html.erb
<div class="top-contents">
  <div class="main-messages">
    <h1>業務報告の簡素化・社内コミュニケーションツール</h1>
    <p>シンプルな業務報告で報告業務に手間を取らせません</p>
      <p>ちょっとした社内連絡もメンバー全員で共有できます</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SIESTA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-left">
        <h1>SIESTA</h1>
      </div>
      <% if user_signed_in? %>
        <div class="header-right">
          お疲れ様です、<%= current_user.name %>さん
          <%= link_to "報告一覧", reports_path, method: :get, class: "btn report-index" %>
          <%= link_to "業務報告", new_report_path, method: :get, class: "btn entry" %>
          <%= link_to "連絡掲示板", boards_path, method: :get, class: "btn bbs" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn login" %>
        </div>
      <% else %>
        <div class="header-right">
          <%= link_to "新規登録", "/users/sign_up", method: :get, class: "btn entry" %>
          <%= link_to "ログイン", "/users/sign_in", method: :get, class: "btn login" %>
        </div>
      <% end %>
    </header>
    <%= yield %>
    <footer>
      <p>SIESTA</p>
    </footer>
  </body>
</html>

app/views/reports/edit.html.erb
<div class="new-contents">
  <div class="report-form">
    <%= form_with(model: @report, local: true) do |f| %>
      行先<br>
      <%= f.select :client, [["某会社", "某会社"], ["某工場", "某工場"], ["某代理店", "某代理店"], ["某小売店", "某小売店"], ["その他（備考に記載）", "その他"]], include_blank: "選択して下さい", class: "select" %><br>
      面会者<br>
      <%= f.text_field :client_person, placeholder: "面会者" %><br>
      用件<br>
      <%= f.select :business, [["製品紹介", "製品紹介"], ["情報提供", "情報提供"], ["クレーム対応", "クレーム対応"], ["納品", "納品"],["その他（備考に記載）", "その他"]], include_blank: "選択して下さい", class: "select" %><br>
      結果<br>
      <%= f.select :result, [["進捗", "進捗"], ["変わらず", "変わらず"], ["後退", "後退"]], include_blank: "選択して下さい" %><br>
      備考<br>
      <%= f.text_area :note, placeholder: "何かあれば入力" %><br>
      <%= f.submit '報告'%>
    <% end %>
  </div>
</div>

app/views/reports/index.html.erb
<div class="main-contents">
  <%= form_with(url: search_reports_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "備考欄キーワード", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <% @reports.each do |report| %>
    <div class="dailyReport">
      <p><%= report.created_at.strftime("%Y-%m-%d %H:%M") %></p>
      <h1>報告者</h1>
        <p><%= report.user.name %></p>
      <h1>行先</h1>
        <p><%= report.client %></p>
      <h1>面会者</h1>
        <p><%= report.client_person %></p>
      <h1>用件</h1>
        <p><%= report.business %></p>
      <h1>結果</h1>
        <p><%= report.result %></p>
      <h1>備考</h1>
        <p><%= report.note %></p>
      <div align="right">
        <%= link_to report_path(report.id), method: :get do %>
          <i class="far fa-comment"></i>
        <% end %>
        <% if user_signed_in? && current_user.id == report.user_id %>
          <%= link_to edit_report_path(report.id), method: :get do %>
            <i class="far fa-edit"></i>
          <% end %>
          <%= link_to report_path(report.id), method: :delete do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/reports/new.html.erb
<div class="new-contents">
  <div class="report-form">
    <%= form_with(model: @report, local: true) do |f| %>
      行先<br>
      <%= f.select :client, [["某会社", "某会社"], ["某工場", "某工場"], ["某代理店", "某代理店"], ["某小売店", "某小売店"], ["その他（備考に記載）", "その他"]], include_blank: "選択して下さい" %><br>
      面会者<br>
      <%= f.text_field :client_person, placeholder: "面会者" %><br>
      用件<br>
      <%= f.select :business, [["製品紹介", "製品紹介"], ["情報提供", "情報提供"], ["クレーム対応", "クレーム対応"], ["納品", "納品"],["その他（備考に記載）", "その他"]], include_blank: "選択して下さい" %><br>
      結果<br>
      <%= f.select :result, [["進捗", "進捗"], ["変わらず", "変わらず"], ["後退", "後退"]], include_blank: "選択して下さい" %><br>
      備考<br>
      <%= f.text_area :note, placeholder: "何かあれば入力" %><br>
      <%= f.submit '報告'%>
    <% end %>
  </div>
</div>

app/views/reports/search.html.erb
<div class="main-contents">
  <%= form_with(url: search_reports_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "備考欄キーワード", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <% @reports.each do |report| %>
    <div class="dailyReport">
      <p><%= report.created_at.strftime("%Y-%m-%d %H:%M") %></p>
      <h1>報告者</h1>
        <p><%= report.user.name %></p>
      <h1>行先</h1>
        <p><%= report.client %></p>
      <h1>面会者</h1>
        <p><%= report.client_person %></p>
      <h1>用件</h1>
        <p><%= report.business %></p>
      <h1>結果</h1>
        <p><%= report.result %></p>
      <h1>備考</h1>
        <p><%= report.note %></p>
      <div align="right">
        <%= link_to report_path(report.id), method: :get do %>
          <i class="far fa-comment"></i>
        <% end %>
        <% if user_signed_in? && current_user.id == report.user_id %>
          <%= link_to edit_report_path(report.id), method: :get do %>
            <i class="far fa-edit"></i>
          <% end %>
          <%= link_to report_path(report.id), method: :delete do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/reports/show.html.erb
<div class="main-contents">  
  <div class="dailyReport">
    <p><%= @report.created_at.strftime("%Y-%m-%d %H:%M") %></p>
    <h1>報告者</h1>
      <p><%= @report.user.name %></p>
    <h1>行先</h1>
      <p><%= @report.client %></p>
    <h1>面会者</h1>
      <p><%= @report.client_person %></p>
    <h1>用件</h1>
      <p><%= @report.business %></p>
    <h1>結果</h1>
      <p><%= @report.result %></p>
    <h1>備考</h1>
      <p><%= @report.note %></p>
    <div align="right">
      <% if current_user.id == @report.user_id %>
        <%= link_to edit_report_path(@report.id), method: :get do %>
          <i class="far fa-edit"></i>
        <% end %>
        <%= link_to report_path(@report.id), method: :delete do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="comment-form">
    <%= form_with(model: [@report, @comment], local: true) do |form| %>
      <%= form.text_area :text, placeholder: "コメントを入力", rows: "2" %><br>
      <%= form.submit "コメントする", class: "submit-btn" %>
    <% end %>
  </div>
  <div class="comments">
    <h3 align="center">＜コメント一覧＞</h3>
    <% if @comments %>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= comment.user.name %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    <% end %>
  </div>
</div> 

 